env:
  IMAGE_NAME: ots-image
  ID_PROJECT: terraform-project-atserge1
  PROJECT_REPO: ots-project-repo

name: Test
on:
  push:
    branches: [ atserge1 ]
    
  workflow_dispatch:
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.ID_PROJECT }}
        export_default_credentials: true
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.9
        
    - name: Terraform init
      run: |- 
        cd terraform-registry
        terraform init
      
    - name: Debug
      run: echo "$GITHUB_REF"

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |-
        cd terraform-registry 
        terraform destroy -auto-approve -input=false
        terraform apply -auto-approve -input=false
      
    - name: Build Docker Image    
      run: |-
        cd docker
        docker build -t ${{ env.IMAGE_NAME }}:latest .
    
    - name: Debug
      run: docker images
  
    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
    
    - name: Tag and Push Docker Image to Registry
      run: |-
  
        docker image tag ${{ env.IMAGE_NAME }}:latest us-central1-docker.pkg.dev/${{ env.ID_PROJECT }}/${{ env.PROJECT_REPO }}/${{ env.IMAGE_NAME }}:latest
        docker image tag ${{ env.IMAGE_NAME }}:latest us-central1-docker.pkg.dev/${{ env.ID_PROJECT }}/${{ env.PROJECT_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push us-central1-docker.pkg.dev/${{ env.ID_PROJECT }}/${{ env.PROJECT_REPO }}/${{ env.IMAGE_NAME }}:latest
        docker push us-central1-docker.pkg.dev/${{ env.ID_PROJECT }}/${{ env.PROJECT_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        
